# app/Dockerfile

FROM python:3.9-slim

WORKDIR /frontend

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*


RUN pip3 install -r requirements.txt

COPY . .
EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["python","-m","streamlit", "run", "app/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
